#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-File
Version  : 1.443
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/Test-File-1.443.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/Test-File-1.443.tar.gz
Summary  : 'test file attributes'
Group    : Development/Tools
License  : Artistic-1.0-Perl Artistic-2.0
Requires: perl-Test-File-doc
BuildRequires : perl(Test::utf8)

%description
See the tests in the t/ directory for examples until I add some more.

%package doc
Summary: doc components for the perl-Test-File package.
Group: Documentation

%description doc
doc components for the perl-Test-File package.


%prep
%setup -q -n Test-File-1.443

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Test/File.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
